name: Context Actions

on: push

run-name: "Context Actions Information"

jobs:
  run_context:
    runs-on: ubuntu-latest
    steps:
      - name: Context and Expressions
        id: context-expressions
        run: |
          echo "${{ toJson(github) }}"
          echo "${{ toJson(runner) }}"
          echo "${{ toJson(job) }}"
      - name: Show Steps Context
        id: steps-context
        run: echo "${{ toJson(steps) }}"
