name: Environment Variables 2

run-name: Environment Variables 2

on: push

env:
  WF_GLOBAL_ENV: Global Value # Глобальная переменная для всего ворфлоу

jobs:
  first_job_name:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Job Value # Значение переменной JOB_ENV будет доступно в первом Job
    steps:
      - name: First Step
        run: echo "FIRST_STEP_VAR=First Step Value" >> "$GITHUB_ENV"
      - name: Second Step
        env:
          SECOND_STEP_VAR: Second Step Value
        run: |
          echo $GITHUB_REF
          echo "${{ github.ref }}"
          echo $WF_GLOBAL_ENV
          echo "${{ env.WF_GLOBAL_ENV }}"
          echo $JOB_ENV
          echo $SECOND_STEP_VAR
          echo $FIRST_STEP_VAR
