name: Fourth Workflow

on:
  workflow_run:
    workflows:
      - Third Workflow
    types:
      - completed

jobs:
  run_job_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Show message
        run: echo "Hello from fourth workflow"
