name: Fourth Workflow

on:
  # Событие выполнения workflow
  workflow_run:
    # Массив workflows с их идентификаторами
    workflows:
      - Third Workflow
    # Состояние workflow - в данном случае состояние completed, то есть workflow завершен
    # есть еще одно состояние workflow - in_progress
    types:
      - completed

jobs:
  run_job_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Show message
        run: echo "Hello from fourth workflow"
