name: secondo_workflow

on:
  workflow_run:
    workflows:
      - primo_workflow
    types:
      - completed

jobs:
  run_secondo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Show system info
        run: uname -a
