name: secondo_workflow

on:
  workflow_run:
    workflows:
      - primo_workflow
    types:
      - completed

jobs:
  success_job:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Show message
        run: echo "Success job"
  failure_job:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Show message
        run: echo 'Failure job'
